# Extend default settings for all of my personal repositories defined in .github/settings.yml
_extends: .github:common-settings.yaml

repository:
  name: Presentations
  description: A collection of presentations I've given.
  homepage: https://mrbro.dev/Presentations/

  topics: >-
    react,
    meetup,
    blockchain,
    presentations,
    ethereum-classic,
    ethereum,
    opencode,
    cheap-llms,
    slides,
    slidev,

  archived: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts: ['Build', 'Test', 'Renovate / Renovate']
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
