---
name: CI
'on':
  pull_request_target:
    types: [opened, edited, closed]
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Blockchain-Meetup-Feb-2017
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.16.0 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Blockchain-Meetup-Feb-2017
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.16.0 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
