---
name: CI
'on':
  pull_request_target:
    types: [opened, edited, closed]
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Blockchain-Meetup-Feb-2017
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.14.2 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Blockchain-Meetup-Feb-2017
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.14.2 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
