---
name: CI
'on':
  pull_request_target:
    types: [opened, edited, closed]
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Blockchain-Meetup-Feb-2017
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 20.11.0 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Blockchain-Meetup-Feb-2017
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 20.11.0 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
